# proba
on: [push, pull_request]
jobs:
   run:
     runs-on: [self-hosted, vm]
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
       - name: Proba
         run: cd ~ && touch test.txt
       - name: Run simple command
         run: echo "Workflow uspe≈°no zagnan na Linux self-hosted runnerju"
